### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by PeterXiaosa** [shinnytech/shinny-futures-android#2]
想请问下小哥哥们，是不是漏传了一些包。比如com.shinnytech.futures.databinding.*。没有找到这个包呀。然后里面的一些dataBinding类就找不到了......

**Comment by shinny-chenli** [comment]
1. databinding是Google内置的开发包，用于数据与视图的绑定，简化代码
2. 我这边试了一下，能够编译通过
3. 您可以试试：首先进行`Invalidate Caches and Restart`，然后重新下载项目进行编译

**Comment by shinny-chenli** [comment]
这个类是AS自动生成的，位于项目的build目录下，类似于
![image](https://user-images.githubusercontent.com/13851495/45604165-53c95700-ba64-11e8-84cf-d085809ab9fb.png)
之前编译错误应该是AS没有生成或生成错误，删掉缓存重启就是让AS重新生成一下这个类

**Comment by PeterXiaosa** [comment]
嗯，看到了谢谢。是我孤陋寡闻，不了解dataBinding会自动生成，谢谢~
